# Generated by Django 4.1.1 on 2022-10-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=4)),
                ('major', models.CharField(max_length=5)),
                ('specialization', models.CharField(max_length=20)),
                ('minor', models.CharField(max_length=5)),
                ('credit_hours', models.IntegerField()),
                ('semester_taught', models.CharField(max_length=1)),
                ('required_passing_grade', models.CharField(max_length=2)),
            ],
        ),
    ]
