# Generated by Django 4.1.1 on 2022-10-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='major',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='minor',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='required_passing_grade',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='semester_taught',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='year',
        ),
        migrations.AlterField(
            model_name='classes',
            name='Course',
            field=models.CharField(max_length=20),
        ),
    ]
