# Generated by Django 4.1.1 on 2022-10-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_remove_classes_credit_hours_remove_classes_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Credit_Hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Major',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Required_Passing_Grade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='Semester_Taught',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='Course',
            field=models.CharField(max_length=8),
        ),
    ]
